### ISSUE TITLE
ADT Full résolution ?

### ISSUE THREAD

**Issue by fabienroots** [adafruit/Adafruit_ADT7410#4]
Hi,

I try this code and many other, but is always the same issue ... the ADT can provide a résolution of 0.006 °c but this code give only a résolution of 0.06°c. 
How i can improve this ?

Best regards

**Comment by ladyada** [comment]
![image](https://user-images.githubusercontent.com/1214161/69750024-c24e7e00-1119-11ea-8fa1-432c9c72ac48.png)


resolution is 0.0625 in datasheet

**Comment by fabienroots** [comment]
yeah it's the 13 bits résolution, i buy this for the 16 bits résolutions to have the 0.0076 °C ! 
MAny maker's library take yours for exemple and never rish this 0.0076°C
But with the good registery callback i make this  ...

So i think this issue is not close because this sensor have a 16bits résolution to, and yours library cant read this ...

**Comment by ladyada** [comment]
ok please submit a PR for adding it! we'll take a look!

**Comment by DeStuiper** [comment]
Hi, any news to this? Didnt find anyone who actually got a 16bit reading ... would be too bad because of course one buys this thing for its high temperature range including resolution.
thx
